
- name: assure config directory exists
  file: path={{ INSTALL_PATH }} state=directory

# deploy landingpage
- name: git landingpage
  git: repo=git@github.com:yomypopcorn/landingpage.git update=yes dest=/var/www/landingpage

- name: landingpage nginx config
  template:
    src=landingpage-nginx.j2
    dest=/etc/nginx/sites-available/landingpage

- name: enable landingpage nginx
  file:
    src=/etc/nginx/sites-available/landingpage
    dest=/etc/nginx/sites-enabled/landingpage
    state=link
  notify:
    - reload nginx


# deploy yo-service
- name: git yo-service
  git: repo=git@github.com:yomypopcorn/yo-service.git update=yes dest={{ INSTALL_PATH }}/yo-service

- name: install app dependencies
  npm: path={{ INSTALL_PATH }}/yo-service state=present

- name: restart yo.service
  service: name=yo state=restarted enabled=yes

- name: yo-service nginx config
  template:
    src=yo-service-nginx.j2
    dest=/etc/nginx/sites-available/yo-service

- name: enable landingpage nginx
  file:
    src=/etc/nginx/sites-available/yo-service
    dest=/etc/nginx/sites-enabled/yo-service
    state=link
  notify:
    - reload nginx


# deploy yomypopcorn-scanner
- name: git yomypopcorn-scanner
  git: repo=git@github.com:yomypopcorn/yomypopcorn-scanner.git update=yes dest={{ INSTALL_PATH }}/scanner

- name: install scanner dependencies
  npm: path={{ INSTALL_PATH }}/scanner state=present

- name: restart yomypopcorn-scanner.service
  service: name=yomypopcorn-scanner state=restarted enabled=yes

