---
- name: host setup
  hosts: yo1
  vars_files:
    - vars.yml
  tasks:
    - name: update apt cache
      apt: update_cache=yes
  roles:
    - sshd
    - authorized-keys
    - htop
    - base
    - vim
    - yo-service
    - yo-scanner
    - landingpage
