---
- name: host setup
  hosts: yo1
  vars_files:
    - vars.yml
  tasks:
    - name: update apt cache
      apt: update_cache=yes
  roles:
    - timezone
    - { role: kamaln7.swapfile, swapfile_size: 1GB, swapfile_swappiness: 10 }
    - sshd
    - authorized-keys
    - htop
    - base
    - vim
    - bistre
    - ympc-app
    - ympc-scanner
    - ympc-dispatcher
    - ympc-kueui
    - ympc-landingpage
