---
- name: remove the current localtime file
  file:
    dest=/etc/localtime
    state=absent

- name: symlink the correct localtime (/etc/localtime)
  file:
    src=/usr/share/zoneinfo/{{TIME_ZONE}}
    dest=/etc/localtime
    state=link
    owner=root
    group=root
    mode=0644

- name: install tzdata
  apt: name=tzdata state=present

- name: update the hardware clock
  command: dpkg-reconfigure -f noninteractive tzdata
