- name: ensure rsync is installed
  apt: name=rsync state=present

- name: ensure vim is installed
  apt: name=rsync state=present

- name: ensure git is installed
  apt: name=git state=present

- name: ensure redis-server is installed
  apt: name=redis-server state=present

- name: ensure redis-tools is installed
  apt: name=redis-tools state=present

- name: ensure make is installed
  apt: name=make state=present

- name: ensure g++ is installed
  apt: name=g++ state=present

- name: install keys for {{ item }}
  authorized_key: user=root key=https://github.com/{{item}}.keys
  with_items: ADMINS

- name: "deploy systemd for yo-service"
  template: src=yo.service.j2 dest=/etc/systemd/system/yo.service

- name: "deploy systemd unit for yomypopcorn-scanner"
  template: src=yomypopcorn-scanner.service.j2 dest=/etc/systemd/system/yomypopcorn-scanner.service

- name: "config for scanner"
  template: src=yomypopcorn-scannerrc.j2 dest=/etc/yomypopcorn-scannerrc

- name: "config for service"
  template: src=yomypopcorn-servicerc.j2 dest=/etc/yomypopcorn-servicerc

# @ todo: use notify
- name: systemd reload-daemon
  command: systemctl daemon-reload
